[font]
normal = { family = "monospace", style = "normal" }
bold = { family = "monospace", style = "bold" }
italic = { family = "monospace", style = "italic" }
size = 16

[window]
padding = { x = 10, y = 10 }
dynamic_padding = true

[colors.primary]
background = "#1E1D1D"
foreground = "#EAE7E0"

[colors.normal]
black   = "#1E1D1D"
red     = "#7F7979"
green   = "#5F5B6B"
yellow  = "#C1BDB3"
blue    = "#3D3B3C"
magenta = "#7F7979"
cyan    = "#5F5B6B"
white   = "#EAE7E0"

[colors.bright]
black   = "#3D3B3C"
red     = "#7F7979"
green   = "#C1BDB3"
yellow  = "#EAE7E0"
blue    = "#5F5B6B"
magenta = "#C1BDB3"
cyan    = "#7F7979"
white   = "#FFFFFF"

[colors.cursor]
text = "#1E1D1D"
cursor = "#EAE7E0"

[colors.selection]
text = "#1E1D1D"
background = "#EAE7E0"

[colors.footer_bar]
background = "#3D3B3C"
foreground = "#EAE7E0"

[colors.vi_mode_cursor]
text = "#1E1D1D"
cursor = "#7F7979"

